channels:
- conda-forge
dependencies:
- python=3.9.18
- pip<=24.0
- pip:
  - mlflow==2.9.2
  - cloudpickle==2.2.1
  - importlib-metadata==7.0.1
  - numpy==1.26.3
  - packaging==23.1
  - psutil==5.9.0
  - pyyaml==6.0.1
  - scikit-learn==1.3.0
  - scipy==1.11.4
name: mlflow-env
